name: Redeploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/anis211/carmax:latest
          platforms: linux/amd64

      - name: Trigger Deployment on DigitalOcean
        env:
          DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -H "Authorization: Bearer $DO_API_TOKEN" \
            -d '{"type":"STANDARD_APP"}' \
            "https://api.digitalocean.com/v2/apps/your-app-id/deployments"
